;#Include *i %A_ScriptDir%\Plugins\brackets.ahk
#Include *i %A_ScriptDir%\Plugins\my-edit.ahk
;#Include *i %A_ScriptDir%\Plugins\fn.ahk
#Include *i %A_ScriptDir%\Plugins\git_alias.ahk
;#Include *i %A_ScriptDir%\Plugins\hotString.ahk
#Include *i %A_ScriptDir%\Plugins\IME.ahk
;#Include *i %A_ScriptDir%\Plugins\keybd_mouse.ahk
#Include *i %A_ScriptDir%\Plugins\main.ahk
;#Include *i %A_ScriptDir%\Plugins\numpad.ahk
;#Include *i %A_ScriptDir%\Plugins\others.ahk
;#Include *i %A_ScriptDir%\Plugins\temp.ahk
;#Include *i %A_ScriptDir%\Plugins\toggle.ahk
#Include *i %A_ScriptDir%\Plugins\my-keybind.ahk
#Include *i %A_ScriptDir%\Plugins\my-launcher.ahk
